const state = { products: [], source: '', favorites: new Set(JSON.parse(localStorage.getItem('bhima-favorites') || '[]')) };
const $ = (id) => document.getElementById(id);
const money = (value) => value == null ? '--' : new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 0 }).format(value);
const ratio = (value) => value == null ? '--' : `${(value * 100).toFixed(2)}%`;
const va = (value) => value == null ? '--' : `${((1 - value) * 100).toFixed(2)}%`;
const purityOf = (name) => (name.match(/\b(18\s*kt|22\s*kt|22\s*k|24\s*kt)\b/i) || [])[1]?.replace(/\s+/g, '').toUpperCase() || 'Other';
const categoryOf = (name) => { const terms = ['necklace','chain','bangle','ring','earring','stud','drops','mangalsutra','haar am','haaram','pendant','bracelet','coin','anklet','nosepin']; const found = terms.find((term) => name.toLowerCase().includes(term)); return found === 'haar am' ? 'Haaram' : found ? found[0].toUpperCase() + found.slice(1) : 'Other'; };
const audienceOf = (name) => { const l = name.toLowerCase(); if (l.includes('baby') || l.includes('kids') || l.includes('kid') || l.includes('child')) return 'Kids'; if (l.includes('women') || l.includes('woman')) return 'Women'; if (l.includes('unisex')) return 'Unisex'; if (l.includes(' men') || l.startsWith('men ') || l.includes('for men') || l.includes(' gents')) return 'Men'; return 'Unisex/Other'; };
function populateSelect(id, values) { const select = $(id); [...new Set(values)].sort().forEach((value) => select.insertAdjacentHTML('beforeend', `<option value="${value}">${value}</option>`)); }
function saveFavorites() { localStorage.setItem('bhima-favorites', JSON.stringify([...state.favorites])); }
function filteredProducts() { const query = $('searchInput').value.trim().toLowerCase(); const minPrice = Number($('minPrice').value) || 0; const maxPrice = Number($('maxPrice').value) || Infinity; const minRatio = Number($('minRatio').value) / 100; const purity = $('puritySelect').value; const category = $('categorySelect').value; const audience = $('audienceSelect').value; const favoritesOnly = $('favoritesOnly').checked; const filtered = state.products.filter((product) => { const name = product.name || ''; return product.value_ratio != null && (!query || name.toLowerCase().includes(query)) && (product.grand_total || 0) >= minPrice && (product.grand_total || 0) <= maxPrice && product.value_ratio >= minRatio && (!purity || purityOf(name) === purity) && (!category || categoryOf(name) === category) && (!audience || audienceOf(name) === audience) && (!favoritesOnly || state.favorites.has(product.url)); }); const sort = $('sortSelect').value; return filtered.sort((a, b) => sort === 'price-low' ? a.grand_total - b.grand_total : sort === 'price-high' ? b.grand_total - a.grand_total : sort === 'name' ? a.name.localeCompare(b.name) : b.value_ratio - a.value_ratio); }
function render() { const products = filteredProducts(); $('visibleCount').textContent = products.length.toLocaleString('en-IN'); $('bestRatio').textContent = products[0] ? ratio(products[0].value_ratio) : '--'; $('bestVa').textContent = products[0] ? va(products[0].value_ratio) : '--'; const grid = $('productGrid'); if (!products.length) { grid.innerHTML = '<div class="empty">No products match these filters.</div>'; return; } grid.innerHTML = ''; products.forEach((product, index) => { const card = $('productTemplate').content.cloneNode(true); card.querySelector('.rank').textContent = `#${index + 1}`; card.querySelector('.product-name').textContent = product.name; card.querySelector('.purity-chip').textContent = purityOf(product.name); card.querySelector('.category-chip').textContent = categoryOf(product.name); const audChip = card.querySelector('.audience-chip'); audChip.textContent = audienceOf(product.name); audChip.style.display = ''; card.querySelector('.grand-total').textContent = money(product.grand_total); card.querySelector('.gold-value').textContent = money(product.gold_value); card.querySelector('.value-ratio').textContent = ratio(product.value_ratio); card.querySelector('.va-value').textContent = va(product.value_ratio); const link = card.querySelector('.product-link'); link.href = product.url; const save = card.querySelector('.save-button'); const saved = state.favorites.has(product.url); save.textContent = saved ? '★' : '☆'; save.classList.toggle('saved', saved); save.addEventListener('click', () => { saved ? state.favorites.delete(product.url) : state.favorites.add(product.url); saveFavorites(); render(); }); grid.appendChild(card); }); }
async function load() { $('sourceBadge').textContent = 'Loading data'; try { const response = await fetch(`/api/products?time=${Date.now()}`); const data = await response.json(); state.products = data.products || []; state.source = data.source; $('totalCount').textContent = state.products.length.toLocaleString('en-IN'); $('sourceBadge').textContent = data.source ? `Source: ${data.source}` : 'No data'; populateSelect('puritySelect', state.products.map((product) => purityOf(product.name))); populateSelect('categorySelect', state.products.map((product) => categoryOf(product.name))); populateSelect('audienceSelect', state.products.map((product) => audienceOf(product.name))); const invalid = state.products.filter((product) => product.value_ratio == null).length; $('notice').hidden = false; const sizeMsg = 'Size filter: current dataset (3294 products) has no Size/Weight field - only name/url/gold_value/grand_total. Audience (Women/Men/Kids) is derived from name.'; $('notice').textContent = `${invalid} products could not be parsed and are excluded from rankings. ${sizeMsg}`; $('notice').hidden = false; render(); } catch (error) { $('sourceBadge').textContent = 'Data unavailable'; $('notice').hidden = false; $('notice').textContent = `Could not load ranking data: ${error.message}`; } }
function exportView() { const products = filteredProducts(); const headers = ['rank','name','url','gold_value','grand_total','value_ratio','va_proxy']; const rows = products.map((product, index) => [index + 1, product.name, product.url, product.gold_value, product.grand_total, product.value_ratio, 1 - product.value_ratio]); const csv = [headers, ...rows].map((row) => row.map((value) => `"${String(value ?? '').replaceAll('"', '""')}"`).join(',')).join('\n'); const link = document.createElement('a'); link.href = URL.createObjectURL(new Blob([csv], { type: 'text/csv' })); link.download = 'bhima-gold-filtered.csv'; link.click(); URL.revokeObjectURL(link.href); }
['searchInput','minPrice','maxPrice','puritySelect','categorySelect','audienceSelect','favoritesOnly','sortSelect'].forEach((id) => $(id).addEventListener('input', render)); $('minRatio').addEventListener('input', () => { $('ratioOutput').value = `${$('minRatio').value}%`; $('ratioOutput').textContent = `${$('minRatio').value}%`; render(); }); $('clearButton').addEventListener('click', () => { ['searchInput','minPrice','maxPrice'].forEach((id) => $(id).value = ''); $('minRatio').value = 0; $('ratioOutput').textContent = '0%'; $('puritySelect').value = ''; $('categorySelect').value = ''; $('audienceSelect').value = ''; $('favoritesOnly').checked = false; render(); }); $('refreshButton').addEventListener('click', load); $('exportButton').addEventListener('click', exportView); load();
